import bpy
from .tools import (
    modeling,
    sculpt,
    object, mesh, material, light, modifier,
    physics, node, animation, collection,
    scene, selection, constraint, io, asset
)

class AtomicEngine:
    def __init__(self):
        self.tools = {
            # Object & Transform
            "create_primitive": object.create_primitive,
            "transform_object": object.transform_object,
            "delete_object": object.delete_object,
            "duplicate_object": object.duplicate_object,
            "rename_object": object.rename_object,
            "set_parent": object.set_parent,
            "clear_parent": object.clear_parent,
            "hide_object": object.hide_object,
            "move_to_collection": object.move_to_collection,
            "apply_transform": object.apply_transform,
            "clear_transform": object.clear_transform,
            "set_origin": object.set_origin,
            "add_empty": object.add_empty,
            "join_objects": object.join_objects,
            "separate_objects": object.separate_objects,
            "make_instance": object.make_instance,
            "convert_object": object.convert_object,
            "align_objects": object.align_objects,
            "randomize_transform": object.randomize_transform,
            "copy_transforms": object.copy_transforms,
            "snap_to_cursor": object.snap_to_cursor,
            "snap_cursor_to_object": object.snap_cursor_to_object,
            "get_object_dimensions": object.get_object_dimensions,
            "set_object_dimensions": object.set_object_dimensions,
            "set_display_color": object.set_display_color,
            "set_draw_type": object.set_draw_type,
            "make_local": object.make_local,
            "set_object_pass_index": object.set_object_pass_index,

            # Mesh Ops
            "add_torus": mesh.add_torus,
            "add_monkey": mesh.add_monkey,
            "add_icosphere": mesh.add_icosphere,
            "subdivide_mesh": mesh.subdivide_mesh,
            "shade_smooth": mesh.shade_smooth,
            # Mesh Cleanup
            "remove_doubles": mesh.remove_doubles,
            "fill_holes": mesh.fill_holes,
            "recalculate_normals": mesh.recalculate_normals,
            "mesh_cleanup": mesh.mesh_cleanup,
            "decimate_mesh": mesh.decimate_mesh,
            "triangulate_mesh": mesh.triangulate_mesh,

            # Materials & Textures
            "assign_material": material.assign_material,
            "remove_material": material.remove_material,
            "set_material_property": material.set_material_property,
            "add_texture_image": material.add_texture_image,
            "set_world_background": material.set_world_background,

            # Lighting & Camera
            "add_light": light.add_light,
            "set_light_property": light.set_light_property,
            "add_camera": light.add_camera,
            "set_active_camera": light.set_active_camera,

            # Modifiers
            "add_modifier": modifier.add_modifier,
            "remove_modifier": modifier.remove_modifier,
            "apply_modifier": modifier.apply_modifier,
            "add_subsurf_modifier": modifier.add_subsurf_modifier,
            "add_solidify_modifier": modifier.add_solidify_modifier,
            "add_bevel_modifier": modifier.add_bevel_modifier,
            "add_boolean_modifier": modifier.add_boolean_modifier,
            "add_array_modifier": modifier.add_array_modifier,
            "add_mirror_modifier": modifier.add_mirror_modifier,
            "add_decimate_modifier": modifier.add_decimate_modifier,
            "add_displace_modifier": modifier.add_displace_modifier,
            "add_mask_modifier": modifier.add_mask_modifier,
            "add_multires_modifier": modifier.add_multires_modifier,
            "add_remesh_modifier": modifier.add_remesh_modifier,
            "add_screw_modifier": modifier.add_screw_modifier,
            "add_skin_modifier": modifier.add_skin_modifier,
            "add_triangulate_modifier": modifier.add_triangulate_modifier,
            "add_wireframe_modifier": modifier.add_wireframe_modifier,
            "add_simple_deform_modifier": modifier.add_simple_deform_modifier,
            "add_curve_modifier": modifier.add_curve_modifier,
            "add_warp_modifier": modifier.add_warp_modifier,
            "add_wave_modifier": modifier.add_wave_modifier,
            "add_cast_modifier": modifier.add_cast_modifier,
            "add_surface_deform_modifier": modifier.add_surface_deform_modifier,
            "add_mesh_deform_modifier": modifier.add_mesh_deform_modifier,
            "add_smooth_corrective_modifier": modifier.add_smooth_corrective_modifier,
            "add_laplacian_smooth_modifier": modifier.add_laplacian_smooth_modifier,
            "add_hook_modifier": modifier.add_hook_modifier,
            "add_lattice_modifier": modifier.add_lattice_modifier,
            "add_shrinkwrap_modifier": modifier.add_shrinkwrap_modifier,
            "add_data_transfer_modifier": modifier.add_data_transfer_modifier,
            "add_weighted_normal_modifier": modifier.add_weighted_normal_modifier,
            "apply_boolean_difference": modifier.apply_boolean_difference,
            "apply_boolean_slice": modifier.apply_boolean_slice,

            # Physics
            "setup_physics": physics.setup_physics,
            "setup_rigid_body_world": physics.setup_rigid_body_world,
            "add_rigid_body_constraint": physics.add_rigid_body_constraint,
            "setup_cloth": physics.setup_cloth,
            "setup_dynamic_paint_canvas": physics.setup_dynamic_paint_canvas,
            "setup_dynamic_paint_brush": physics.setup_dynamic_paint_brush,
            "add_ocean_modifier": physics.add_ocean_modifier,
            "setup_particle_system": physics.setup_particle_system,
            "explode_object": physics.explode_object,
            "bake_all_physics": physics.bake_all_physics,
            "setup_collision": physics.setup_collision,
            "add_force_field": physics.add_force_field,
            "setup_soft_body": physics.setup_soft_body,
            "setup_fluid_domain": physics.setup_fluid_domain,
            "setup_fluid_flow": physics.setup_fluid_flow,

            # Nodes
            "setup_geometry_nodes": node.setup_geometry_nodes,
            "create_node": node.create_node,
            "connect_nodes": node.connect_nodes,
            "remove_node": node.remove_node,
            "set_node_property": node.set_node_property,
            "create_node_group": node.create_node_group,
            "add_node_socket": node.add_node_socket,
            "set_node_socket_value": node.set_node_socket_value,
            "template_scatter_objects": node.template_scatter_objects,
            "template_random_displace": node.template_random_displace,
            "frame_nodes": node.frame_nodes,
            "align_nodes": node.align_nodes,
            "mute_node": node.mute_node,

            # Animation
            "set_keyframe": animation.set_keyframe,
            "set_timeline": animation.set_timeline,
            "set_current_frame": animation.set_current_frame,
            "create_action_constraint": animation.create_action_constraint,
            "add_fcurve_modifier": animation.add_fcurve_modifier,
            "clear_animation": animation.clear_animation,
            "set_interpolation_type": animation.set_interpolation_type,
            "bake_action": animation.bake_action,

            # Collections
            "create_collection": collection.create_collection,
            "add_to_collection": collection.add_to_collection,

            # Scene & Rendering
            "get_scene_info": scene.get_scene_info,
            "get_screenshot": scene.get_screenshot,
            "request_feedback": scene.request_feedback,
            "clear_scene": scene.clear_scene,
            "set_render_engine": scene.set_render_engine,
            "set_resolution": scene.set_resolution,
            "render_still": scene.render_still,
            "set_render_samples": scene.set_render_samples,
            "set_denoising": scene.set_denoising,
            "set_color_management": scene.set_color_management,
            "set_output_format": scene.set_output_format,
            "set_background_transparent": scene.set_background_transparent,
            "add_view_layer": scene.add_view_layer,
            "set_render_device": scene.set_render_device,
            "bake_physics": scene.bake_physics,
            "set_viewport_shading": scene.set_viewport_shading,
            "toggle_overlays": scene.toggle_overlays,
            "set_clipping": scene.set_clipping,
            "add_sun_light_env": scene.add_sun_light_env,
            "set_mist_pass": scene.set_mist_pass,
            "setup_compositor_denoise": scene.setup_compositor_denoise,
            "set_render_region": scene.set_render_region,
            "toggle_simplify": scene.toggle_simplify,
            "set_gravity": scene.set_gravity,
            "set_units": scene.set_units,
            "get_render_info": scene.get_render_info,
            "save_file": scene.save_file,
            "audit_scene": scene.audit_scene,

            # Constraints
            "add_constraint": constraint.add_constraint,
            "add_copy_location_constraint": constraint.add_copy_location_constraint,
            "add_copy_rotation_constraint": constraint.add_copy_rotation_constraint,
            "add_copy_scale_constraint": constraint.add_copy_scale_constraint,
            "add_copy_transforms_constraint": constraint.add_copy_transforms_constraint,
            "add_limit_location_constraint": constraint.add_limit_location_constraint,
            "add_limit_rotation_constraint": constraint.add_limit_rotation_constraint,
            "add_limit_scale_constraint": constraint.add_limit_scale_constraint,
            "add_limit_distance_constraint": constraint.add_limit_distance_constraint,
            "add_track_to_constraint": constraint.add_track_to_constraint,
            "add_damped_track_constraint": constraint.add_damped_track_constraint,
            "add_follow_path_constraint": constraint.add_follow_path_constraint,
            "add_shrinkwrap_constraint": constraint.add_shrinkwrap_constraint,
            "add_child_of_constraint": constraint.add_child_of_constraint,
            "add_ik_constraint": constraint.add_ik_constraint,
            "remove_constraint": constraint.remove_constraint,
            "clear_constraints": constraint.clear_constraints,
            "set_constraint_influence": constraint.set_constraint_influence,
            "get_constraints_info": constraint.get_constraints_info,

            # Selection & Context
            "select_object": selection.select_object,
            "deselect_all": selection.deselect_all,
            "set_active_object": selection.set_active_object,
            "select_all": selection.select_all,
            "select_by_type": selection.select_by_type,
            "select_pattern": selection.select_pattern,
            "select_hierarchy": selection.select_hierarchy,
            "invert_selection": selection.invert_selection,
            "get_selected_objects": selection.get_selected_objects,
            "get_active_object": selection.get_active_object,
            "set_mode": selection.set_mode,
            "get_mode": selection.get_mode,
            "hide_unselected": selection.hide_unselected,
            "unhide_all": selection.unhide_all,
            "focus_selected": selection.focus_selected,
            "select_grouped": selection.select_grouped,
            "select_linked": selection.select_linked,
            "select_random": selection.select_random,

            # Import/Export
            "import_obj": io.import_obj,
            "export_obj": io.export_obj,

                                    # Modeling & Construction
            "extrude_faces": modeling.extrude_faces,
            "inset_faces": modeling.inset_faces,
            "loop_cut": modeling.loop_cut,
            "bridge_edge_loops": modeling.bridge_edge_loops,
            "boolean_cut": modeling.boolean_cut,
            "spin_mesh": modeling.spin_mesh,
            "screw_mesh": modeling.screw_mesh,
            "add_bezier_curve": modeling.add_bezier_curve,
            "add_nurbs_path": modeling.add_nurbs_path,
            "set_curve_bevel": modeling.set_curve_bevel,
            "convert_curve_to_mesh": modeling.convert_curve_to_mesh,
            "knife_project": modeling.knife_project,
            "bisect_mesh": modeling.bisect_mesh,
            "edge_split": modeling.edge_split,
            "add_lattice": modeling.add_lattice,
            "apply_lattice_modifier": modeling.apply_lattice_modifier,
            "set_curve_extrude": modeling.set_curve_extrude,
            "extrude_selected_faces": modeling.extrude_selected_faces,
            "inset_selected_faces": modeling.inset_selected_faces,
            "bevel_selected_edges": modeling.bevel_selected_edges,
            "add_loop_cut_slide": modeling.add_loop_cut_slide,
            "spin_selected_region": modeling.spin_selected_region,
            "knife_project_cut": modeling.knife_project_cut,
            "fill_holes": modeling.fill_holes,
            "separate_mesh_selection": modeling.separate_mesh_selection,
            "symmetrize_mesh": modeling.symmetrize_mesh,
            "apply_simple_deform_bend": modeling.apply_simple_deform_bend,
            "apply_lattice_deform": modeling.apply_lattice_deform,
            "create_loft_curve": modeling.create_loft_curve,
            "bend_mesh_along_curve": modeling.bend_mesh_along_curve,

            # Sculpting
            "set_sculpt_mode": sculpt.set_sculpt_mode,
            "select_brush": sculpt.select_brush,
            "set_brush_property": sculpt.set_brush_property,
            "set_stroke_method": sculpt.set_stroke_method,
            "toggle_dyntopo": sculpt.toggle_dyntopo,
            "set_dyntopo_detail": sculpt.set_dyntopo_detail,
            "set_dyntopo_refine_mode": sculpt.set_dyntopo_refine_mode,
            "voxel_remesh": sculpt.voxel_remesh,
            "mask_all": sculpt.mask_all,
            "clear_mask": sculpt.clear_mask,
            "invert_mask": sculpt.invert_mask,
            "smooth_mask": sculpt.smooth_mask,
            "sharpen_mask": sculpt.sharpen_mask,
            "grow_mask": sculpt.grow_mask,
            "shrink_mask": sculpt.shrink_mask,
            "dirty_mask": sculpt.dirty_mask,
            "create_face_set_from_masked": sculpt.create_face_set_from_masked,
            "create_face_set_from_visible": sculpt.create_face_set_from_visible,
            "invert_face_sets": sculpt.invert_face_sets,
            "hide_active_face_set": sculpt.hide_active_face_set,
            "reveal_all_face_sets": sculpt.reveal_all_face_sets,
            "set_sculpt_symmetry": sculpt.set_sculpt_symmetry,
            "trim_box": sculpt.trim_box,
            "trim_lasso": sculpt.trim_lasso,
            "apply_mesh_filter": sculpt.apply_mesh_filter,
            "subdivide_multires": sculpt.subdivide_multires,
            "multires_reshape": sculpt.multires_reshape,
            "set_steady_stroke": sculpt.set_steady_stroke,
            "optimize_sculpt_mesh": sculpt.optimize_sculpt_mesh,
            "get_sculpt_stats": sculpt.get_sculpt_stats,
            "set_brush_falloff": sculpt.set_brush_falloff,
            "set_sculpt_vertex_color": sculpt.set_sculpt_vertex_color,

            # Asset & Materials
            "list_assets": asset.list_assets,
            "import_asset": asset.import_asset,
            "setup_pbr_material": asset.setup_pbr_material,
            "setup_glass_material": asset.setup_glass_material,
            "setup_emission_material": asset.setup_emission_material,
            "setup_car_paint_material": asset.setup_car_paint_material,
        }

    def execute_tool(self, tool_name, args=None):
        if tool_name in self.tools:
            try:
                if args is None: args = {}
                return self.tools[tool_name](**args)
            except Exception as e:
                return {"status": "error", "message": str(e)}
        else:
            return {"status": "error", "message": f"Tool {tool_name} not found"}
